---
- name: restart sssd
  listen: sssd_changed
  service:
    name: sssd
    state: restarted
    enabled: yes

- name: update authconf
  listen: sssd_changed
  shell: "authconfig --enableldap --enableldapauth --enablemkhomedir --update"
  when: ansible_os_family == "RedHat"

- name: oddjob_mkhomedir_changed
  service:
    name: oddjobd
    state: restarted
...
